### ISSUE TITLE
Vscode Debugger is not working

### ISSUE THREAD

**Issue by somaniketan74** [ixartz/Serverless-Boilerplate-Express-TypeScript#10]
Hello,

I cloned your repo and followed the installation steps. Trying to debug via vscode debugger but it's not stopping at the breakpoint. Can you please help me here?

Node version - 14.15.3

launch.json file

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Severless debug",
      "runtimeVersion": "14.15.3",
      "program": "${workspaceFolder}/node_modules/.bin/sls",
      "args": ["offline", "start", "--stage", "offline"],
      "env": { "NODE_ENV": "development" },
      "autoAttachChildProcesses": true,
      "sourceMaps": true,
      "skipFiles": ["<node_internals>/**"],
      "console": "integratedTerminal"
    }
  ]
}

```

**Comment by ixartz** [comment]
Hi @somaniketan74, thank you for your message! Indeed, I confirm I have the same issue on my local computer. The debugger doesn't seems to work anymore.

For the time being, you can use the `debugger;` https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/debugger#syntaxe

I have just tried it and it is working.

I'll investigate and let you know.

**Comment by ixartz** [comment]
Hi @somaniketan74, I just find a fix. It should now be solved. Let me know if it works for you.

**Comment by somaniketan74** [comment]
@ixartz Thanks, It worked :)
