### ISSUE TITLE
No such option: -c

### ISSUE THREAD

**Issue by sharmaraju352** [ixartz/Serverless-Boilerplate-Express-TypeScript#26]
npm run deploy-prod

> serverless-boilerplate-express-typescript@1.2.0 deploy-prod
> run-s deploy:*

> serverless-boilerplate-express-typescript@1.2.0 deploy:db
> dotenv -e .env.production -c -- ts-node --esm scripts/deployDbProd.ts

Usage: dotenv [OPTIONS] COMMAND [ARGS]...
Try 'dotenv --help' for help.

Error: No such option: -c
ERROR: "deploy:db" exited with 2.

**Comment by ixartz** [comment]
@sharmaraju352 Thank you for reporting the issue, it's now solved.
