### ISSUE TITLE
Add Swagger Support

### ISSUE THREAD

**Issue by spaceod** [ixartz/Serverless-Boilerplate-Express-TypeScript#28]
**Issue Description:**
Requesting the addition of Swagger support to the project. Swagger integration would enhance API documentation and streamline development by providing standardized endpoint information.

**Expected Benefits:**
Improved API understanding
Easier client integration
Reduced learning curve for newcomers

**Proposed Implementation:**
Integrate Swagger using libraries like swagger-jsdoc and swagger-ui-express. Include configuration options for customization.

**Contributions:**
I'm interested in contributing to the implementation.

**Comment by ixartz** [comment]
@spaceod Thank you for making the suggestion, I don't have any experience with Swagger. But, I'm totally open to contribution for Swagger, it would be awesome to have Swagger support.

**Comment by ixartz** [comment]
@spaceod do you have any update with Swagger?

**Comment by ixartz** [comment]
It took a whole day to find a solution to integrate Swagger with Serverless Framework. I'm currently testing this feature with Nextless.js. If you are interested by the feature, please contact at contact[at]creativedesignsguru.com
